### ISSUE TITLE
Log4jShell

### ISSUE THREAD

**Issue by PatrickCD14** [bitnami/bitnami-docker-jasperreports#106]
Hi,

JasperReport has got the log4j vulnerability: https://community.jaspersoft.com/wiki/apache-log4j-vulnerability-update-jaspersoft-products

Do you plan an update to fix it or must we to replace manually log4j files on our instance?

Best regards

**Comment by carrodher** [comment]
Hi, thanks for letting us know. We are not applying this kind of patches to the app files bundled as part of the application itself. Once released a new version in the upstream project applies any mitigation (removal of the files, bump the log4j version, etc), we will detect it and trigger the test and release process on our side; but for that, the upstream project should release a new version with the fix they considered.

In the meantime, you can manually apply any mitigation recommended by the upstream devs.

**Comment by ramondelafuente** [comment]
It seems there have been Jasperreports releases with Log4j 2.16

https://support.tibco.com/s/article/TIBCO-Jaspersoft-Mitigation-for-CVE-2021-44228-Log4Shell

**Comment by javsalgar** [comment]
According to the link

```
The recommended solution is to apply the latest hotfix for your corresponding JasperReports Server version:

7.5.2 (also compatible with JRS 7.5.1): https://support.tibco.com/s/hotfixes?id=a014z00000yU9cVAAS
7.8.1 (also compatible with JRS 7.8.0): https://support.tibco.com/s/hotfixes?id=a014z00000yU9caAAC
7.9.1 (also compatible with JRS 7.9.0): https://support.tibco.com/s/hotfixes?id=a014z00000yU9cfAAC
8.0.0: https://support.tibco.com/s/hotfixes?id=a014z00000yUB2NAAW

```

JasperReports 7.8.1 is available in the bitnami/jasperreports repository

**Comment by svdubovik** [comment]
@javsalgar but this image contains log4j-*-2.13.3.jar libs. Looks like log4j.2.13 should be replaced by log4j.2.16 (2.17)

**Comment by n9yty** [comment]
Very anxious to see this implemented. I just updated the docker image, as it was refreshed about six hours ago, thinking this would already be in there but it is not. Please update the image.

**Comment by javsalgar** [comment]
Hi,

We download JasperReports from their repository: 

https://sourceforge.net/projects/jasperserver/files/JasperServer/JasperReports%20Server%20Community%20edition%207.8.1/

As you can see, there are no updates in the 7.8.1 file since October. I believe this should be notified to the JasperReports devs so they can release a new version that our system can download and package.

**Comment by n9yty** [comment]
They outlined the hotfix steps to simply drop in the updated jar files, I thought you could do that in your build to benefit the many people using it. It shouldn't be a difficult process.

**Comment by carrodher** [comment]
According to the information in the [official Log4j site](https://logging.apache.org/log4j/2.x/security.html):
>**Older (discredited) mitigation measures**
>
>This page previously mentioned other mitigation measures, but we discovered that these measures only limit exposure while leaving some attack vectors open.
>
>Other insufficient mitigation measures are: setting system property `log4j2.formatMsgNoLookups` or environment variable `LOG4J_FORMAT_MSG_NO_LOOKUPS` to `true` for releases >= 2.10, or modifying the logging configuration to disable message lookups with `%m{nolookups}, %msg{nolookups}` or `%message{nolookups}` for releases >= 2.7 and <= 2.14.1.
>
>The reason these measures are insufficient is that, in addition to the Thread Context attack vector mentioned above, there are still code paths in Log4j where message lookups could occur: known examples are applications that use `Logger.printf("%s", userInput)`, or applications that use a custom message factory, where the resulting messages do not implement `StringBuilderFormattable`. There may be other attack vectors.
>
>The safest thing to do is to upgrade Log4j to a safe version or remove the `JndiLookup` class from the `log4j-core jar`.

In fact, apart from the existing [CVE-2021-44228](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44228), a new one was filled: [CVE-2021-45046](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046).

Due to this kind of issue and confusing information or mitigation approaches that vary as there is new information, we are not applying any custom patch to the container images and relying on the release cadence of the upstream project. Once released a new version of the upstream application it will be properly tested and released on our side.

In the meantime, you can clone this repo, apply any desired customization and build your own image if possible.
