### ISSUE TITLE
Make version 8.0.0 available

### ISSUE THREAD

**Issue by call-a3** [bitnami/bitnami-docker-jasperreports#107]
**Description**

Jaspersoft released version 8.0.0 in december of 2021. Please make it available as an image.

**Comment by carrodher** [comment]
I'm crossposting the comment provided in the PR:

Thanks for creating this PR, unfortunately, we will need to close it since this process is automated and almost all files are automatically generated by our test & release pipeline.

**Why is not the new major version appearing in the repo?**
The application crashes during the deployment process on top of the Tomcat server, we detected this issue in our internal tests.

The new major version includes some [new features](https://docs.tibco.com/pub/js-jrs-ce/8.0.0/TIB_js-jrs-ce_8.0.0_relnotes.pdf?id=1), such as externalization of certain products (_Audits_). The errors seem to be related to this, so a [new upstream issue has been created](https://community.jaspersoft.com/questions/1191881/jasperreports-server-ce-80-failing-startup). Once we have an answer from the upstream developers and the application works fine, the release process will be unblocked on our side.

**Comment by call-a3** [comment]
Ok, thanks for the explanation. I appreciate it!
I'll keep an eye on the upstream issue and will look forward to the new version appearing.
