### ISSUE TITLE
Log4Shell CVE detected

### ISSUE THREAD

**Issue by demetriusjube** [bitnami/bitnami-docker-jasperreports#115]
### Name and Version

bitnami/jasperreports:7

### What steps will reproduce the bug?

Docker Hub detected that this image has the Log4Shell Vulnerability, as we can see here:
https://hub.docker.com/layers/bitnami/jasperreports/7/images/sha256-576d991f68b7c236c63109625327d580692f348938892a4313a6a5242ac35da7?context=explore

### What is the expected behavior?

No vulnerabilities detected

### What do you see instead?

![image](https://user-images.githubusercontent.com/27288886/155336737-6fcfefb3-ff96-4eaa-bbe1-0a9897515e67.png)

**Comment by carrodher** [comment]
Thanks for letting us know, version 7.x.x contains the CVE since this version was not patched by the application developers. In those cases we can't do anything else since log4j is bundled in the application itself, you can find more info in this issue https://github.com/bitnami/bitnami-docker-jasperreports/issues/106.

Apart from that, we are working on the release of the new major version 8.x.x, we are having some issues already reported [here](https://community.jaspersoft.com/questions/1191881/jasperreports-server-ce-80-failing-startup). Once solved the issues, the new version should be released on our side, and hopefully, the log4Shell issue solved.

I'm marking this ticket as `on-hold` and we'll update it once released the new major version.

**Comment by demetriusjube** [comment]
Thank you for the quick response! Let's hope that the major version solve
this problem. Much appreciated!

Em qui., 24 de fev. de 2022 04:26, Carlos Rodríguez Hernández <
***@***.***> escreveu:

**Comment by carrodher** [comment]
Hi all, I want to let you know the 8.X was already released. In this GH repo, you can find the source code and the container images in the different registries, such as DockerHub.

I'm closing this issue, feel free to create a new one if something doesn't work as expected. Thanks
