### ISSUE TITLE
Log4Shell CVE still detected

### ISSUE THREAD

**Issue by cdeschenes-jea** [bitnami/bitnami-docker-jasperreports#116]
### Name and Version

bitnami/jasperreports:8.0.0

### What steps will reproduce the bug?

When looking at the latest Bitnami Docker Image for JasperReports, I still see the latest tags all have "Log4Shell CVE detected"

I think there are other instances of the log4shell jar files within the image that haven't also been updated to the recent patched versions.

### What is the expected behavior?

Expect the newer versions of the image to no longer show the Log4Shell CVE.

### What do you see instead?

"Log4Shell CVE detected" on all recent tags at https://hub.docker.com/r/bitnami/jasperreports/tags/?page=1&ordering=last_updated

**Comment by carrodher** [comment]
According to the [official JasperReports website](https://community.jaspersoft.com/wiki/apache-log4j-vulnerability-update-jaspersoft-products), version 8.0.0 is still affected by this CVE. Since we are bundling the upstream application without applying any custom patch, the CVE will be present while there is not a fix in the upstream application itself.
