### ISSUE TITLE
Some questions regarding application persisting 

### ISSUE THREAD

**Issue by cemo** [bitnami/bitnami-docker-jasperreports#41]
Hi,

I am trying to understand implications of persisting data in case a removal. Would you add some more information regarding which data is stored in `tomcat_data` and `jasperreports_data`? I thought all information is stored in database and I will just lose `session` data in case a restarting container. 

Thanks

**Comment by dgonzalezruiz** [comment]
Hi @cemo,

We persist the configuration of the deployment so that it does not have to be redone every time the container boots. The container picks up the data in the persistence volumes and restore the installation from the data found in them. 

Also, due to the way we perform the installation of jasperreports, if no data is found in the persistence paths - i.e mounted volumes, the database will be created again from scratch, which is the one the module will have to pick. 

I hope this answer your questions. Let me know if there is anything you didn't fully understand.

**Comment by cemo** [comment]
Actually this is a complementary question to #40.  I am using kubernetes in AWS with a Amazon MySQL Service. I am trying to understand that If do not want to persist `tomcat_data` and `jasperreports_data`, what will be happened in case a reboot or image upgrade. Given the fact that my database is out of cluster and our jasper server is using this database, should I also `tomcat_data` and `jasperreports_data` as well?

**Comment by dgonzalezruiz** [comment]
Hi again @cemo,

Due to the logic in our internal jasperreports installation logic, if there is no such `jasperreports_data` (tomcat one is not required), then the installation will perform all the steps just as in the first boot. This englobes overall database creation and deployment configuration. We are trying to decouple these steps in our most widely used container images, but we haven't started yet working on this on the jasperreports image.

Therefore, not persisting it is not an option. You must persist it in order for your application to work well with our configuration management. But, indeed, it's due to a lack of a feature to support cases like yours, and something that should be feasible.

Is there anything else we can help you with?

**Comment by cemo** [comment]
Thank you so much @dgonzalezruiz, I will give a try soon.
