### ISSUE TITLE
Change the default DB

### ISSUE THREAD

**Issue by nottest** [bitnami/bitnami-docker-jasperreports#48]
Hi,

Any advises on how to configure postgres instead of MariaDB for this image?

Rgds,
Nanthini

**Comment by juan131** [comment]
Hi Nanthini,

I am afraid that this Docker Image doesn't support PostgreSQL yet.

**Comment by gnobre** [comment]
I would also like to configure PostgreSQL instead of MariaDB. The later is not even supported officially by JasperReports

**Comment by juan131** [comment]
Hi @gnobre 

This Docker Image does not support PostgreSQL.

As you can check on the link below, MySQL is one of the supported databases (also Oracle, PostgreSQL, etc.):

> JasperReports Server can access any relational database that supports the SQL query language through the JDBC (Java DataBase Connectivity) API.

https://community.jaspersoft.com/documentation/tibco-jasperreports-server-administrator-guide/v630/data-sources

**Comment by gnobre** [comment]
Thanks @juan131, would be nice to have PostgreSQL support in the features. cheers

**Comment by Adriien-M** [comment]
+1

**Comment by javsalgar** [comment]
Thanks for the feedback, we will consider this for future releases. As this is not a critical feature, we cannot guarantee an ETA.

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-jasperreports#community-supported-solution) since this asset was marked as a "Community supported solution". At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
