### ISSUE TITLE
Changing values in jasperreports/WEB-INF/classes/esapi/*.properties

### ISSUE THREAD

**Issue by Docjones** [bitnami/bitnami-docker-jasperreports#57]
We need to change the security validator behaviour in a property-file in the mentioned directory. Is there a best practice on how to accomplish this

**Comment by juan131** [comment]
Hi @Docjones 

Those properties are under the directory **/opt/bitnami/jasperreports/WEB-INF/classes/esapi** which is not persisted. Therefore, if you change any value there and restart tomcat, the configuration will be lost if you restart the container.


My recommendation is that create a custom script in the [rootfs directory](https://github.com/bitnami/bitnami-docker-jasperreports/tree/master/7/debian-9/rootfs), e.g. **run.sh** and you modify the [app-entrypoint.sh](https://github.com/bitnami/bitnami-docker-jasperreports/blob/master/7/debian-9/rootfs/app-entrypoint.sh) of this image so that script is run when you initialise the image. For instance, modify it so you add under the block below:

```
if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/init.sh" ]]; then
  nami_initialize tomcat mysql-client jasperreports
  info "Starting jasperreports... "
fi
```

Like this:

```
if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/init.sh" ]]; then
  nami_initialize tomcat mysql-client jasperreports
  info "Starting jasperreports... "
fi

## Run custom script
. /run.sh
```

Then, you can implement whatever you need to change in the script. For instance, use the command `sed` to do regex substitutions.

Finally, you just need to build you custom image using the same [Dockerfile](https://github.com/bitnami/bitnami-docker-jasperreports/blob/master/7/debian-9/Dockerfile)

**Comment by Docjones** [comment]
Hi @juan131 and thank you for your answert - however, this pretty much negates the use of using a docker-image, because it prevents us from participating from further updates down the road...

more specifically - there are a lot of application related properties in jasper, which need to be configured.

**Comment by juan131** [comment]
Hi @Docjones 

> it prevents us from participating from further updates down the road...

You'll be using the same Dockerfile. Therefore, you just need to track our daily releases and update it and rebuild the image whenever we do a release
