### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by bluesquid12** [bitnami/bitnami-docker-jasperreports#63]
**Description**

Can this container be modified to use postgres instead of mariadb?

**Comment by rafariossaa** [comment]
Hi @bluesquid12 ,
  Thanks for the suggestion. Currently this is not in our short term roadmap, but I have added it to our backlog in order to study the request.

Best regards,
Rafael Rios Saavedra

**Comment by kershov** [comment]
+1 for PostgreSQL. Could anyone give a direction on how to run Jasper container with Postgres instead of MariaDB? Thnx!

**Comment by marcosbc** [comment]
@kershov Like @rafariossaa mentioned, it's currently not on our roadmap. However, we would like to understand your use case. Why doesn't MariaDB/MySQL work for you?

If you wish, you could check the existing logic and try to modify the container image on your side and contribute the changes. To do that, change the files in the following location:

    /root/.nami/components/com.bitnami.jasperreports/

You would also need to modify the container's Dockerfile to include `postgresql-client` instead of `mysql-client`. Find an example of a container with PostgreSQL Client [here](https://github.com/bitnami/bitnami-docker-odoo/blob/master/13/debian-10/Dockerfile).

**Comment by kershov** [comment]
@marcosbc It's just about our current infrastructure where we use PostgreSQL only. MariaDB works totaly fine, but we still wouldn't want to support another one DB. I'll try your recommendations on modifying the container. Thanks!

**Comment by kershov** [comment]
If someone interested in JRS working with PostgreSQL: https://github.com/kershov/jasperreports

**Comment by jeffreyvdhondel** [comment]
I would like to vote for this request and there is already a PR.

**Comment by sam-cgr** [comment]
This would be really useful
